### ISSUE TITLE
Releasing the adverb / you / swear tokens

### ISSUE THREAD

**Issue by Yueeeeeeee** [bigheiniu/BigData-MDA-WS#1]
Dear authors of MDAWS,

I think your work is very interesting but I fail to reproduce similar results on other datasets without the exact adverb / you / swear tokens. Is it possible to release the adverb / you / swear tokens used in your research so that I can compute & adjust the liwc scores myself? Thanks!

Best
Yueeeeeeee

**Comment by bigheiniu** [comment]
Hi Yue, 
These tokens are from the [LIWC](https://www.liwc.app/). LIWC is a profitable program and we cannot access and release these tokens. 
Best, 
Yichuan

**Comment by Yueeeeeeee** [comment]
Thanks for the info
